# @package _global_
cxr_filepath: 'data/cxr.h5'
txt_filepath: 'data/mimic_impressions.csv'
model_path: None
batch_size: 16
epochs: 10
lr: 1e-4
save_interval: 500
log_interval: 10
save_dir: "./checkpoints/" 
seed: 1234
optimizer: "sgd"
momentum: 0.9
context_length: 77
random_init: False
model_name: "UL"
use_huggingface_bert: False
lock_text: False
lock_vision: False